import {readTabSession} from '../session.mjs';
import {el,labels,accessLabels,date,money,renderProject,updateProjectClock,bucharestISO,bucharestLocal} from '../project-view.mjs';
const $=id=>document.getElementById(id), token=readTabSession(window);
let current=null,offset=0,authorized=false,working=false,viewSequence=0;
const root=$('content');
const displayToggles=[['invoice_enabled','Afișează butonul facturii'],['show_access_policy','Afișează Politica privind accesul, deplasarea și întreruperea lucrărilor'],['show_terms','Afișează Condiții de prestare a serviciilor'],['show_supplier','Afișează informațiile despre furnizor'],['show_review','Afișează invitația la Google Review după finalizare']];
const errors={project_changed_reload:'Proiectul a fost modificat în altă pagină. Reîncarcă înainte de salvare.',change_expiry_before_reactivation:'Accesul este expirat. Editează întâi durata accesului.',password_length_12_128:'Parola trebuie să aibă între 12 și 128 de caractere.',password_copy_requires_reset:'Parola acestui acces nu are încă o copie criptată. Setează parola o dată folosind Setează/resetează parola.',password_copy_unavailable:'Copia parolei nu poate fi decriptată. Setează o parolă nouă.',minimum_agreement_required:'Pentru un minimum diferit de 100 lei, introdu referința acordului scris.',billing_locked_after_start:'Tariful și minimumul nu se mai pot modifica după începerea intervenției.',hourly_start_required:'Începe intervenția înainte de finalizare pentru a măsura timpul.',travel_requires_scheduled:'Deplasarea poate fi activată numai pentru o intervenție programată sau confirmată.',use_start_or_complete:'Folosește acțiunile Începe / Confirmă finalizarea pentru acest status.'};
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
async function api(path='',data,method=data?'POST':'GET') {
 const response=await fetch(window.PETRU_INES_API_ORIGIN+path,{method,credentials:'omit',cache:'no-store',headers:{authorization:'Bearer '+token,...(data?{'content-type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});
 const result=await response.json();if(!response.ok){if([401,403].includes(response.status)){authorized=false;root.replaceChildren();$('nav').hidden=true;throw new Error('Intră în portal cu contul admin și verificarea în doi pași.');}if(response.status===404)throw new Error('Modulul Intervenții punctuale nu este încă activat. Revino în portalul existent.');throw new Error(errors[result.error]||'Cererea nu a putut fi finalizată ('+result.error+').');}return result;
}
const call=(suffix='',data,method)=>api('/api/one-time/admin'+suffix,data,method);
function button(text,action,parent=root,style='secondary') {const b=el('button',text,style);b.type='button';b.addEventListener('click',async()=>{if(working)return;working=true;b.disabled=true;notice('');try{await action();}catch(e){notice(e.message);}finally{working=false;b.disabled=false;}});parent.append(b);return b;}
async function list(){if(!authorized)return;const sequence=++viewSequence;current=null;const data=await call('?offset='+offset);if(sequence!==viewSequence)return;root.replaceChildren();const grid=el('div',undefined,'project-list');root.append(grid);
 for(const p of data.rows){const card=el('article',undefined,'project-card');card.append(el('h2',p.name),el('p',p.client_name+' · '+date(p.scheduled_at)),el('p',labels[p.status]+' · '+money(p.price_bani)+(p.service_options?.billing_mode==='hourly'?' / oră':'')),el('p',`${p.tasks.filter(t=>t.done).length}/${p.tasks.length} sarcini finalizate`),el('p','Acces: '+accessLabels[p.access.status]+(p.access.expires_at?' · expiră '+date(p.access.expires_at):'')));button('Deschide proiect',()=>detail(p.id),card);grid.append(card);}
 if(!data.rows.length)grid.append(el('p','Nu există proiecte în această pagină.','project-empty'));
 const pager=el('div',undefined,'project-actions');root.append(pager);if(offset)button('← Înapoi',async()=>{offset=Math.max(0,offset-30);await list();},pager);if(data.nextOffset!==null)button('Înainte →',async()=>{offset=data.nextOffset;await list();},pager);
}
function clientURL(p){return new URL('../project/?token='+p.access.token,location.href).href;}
async function detail(id){const sequence=++viewSequence;const loaded=await call('/'+id);if(sequence!==viewSequence)return;current=loaded;renderDetail();}
function renderDetail(){const p=current;root.replaceChildren();const card=el('article',undefined,'project-panel');root.append(card);card.append(el('h2',p.name),el('p',p.client_name+' · '+p.phone+(p.email?' · '+p.email:'')),el('p',labels[p.status]+' · '+date(p.scheduled_at)+' · '+money(p.price_bani)+(p.service_options?.billing_mode==='hourly'?' / oră':'')),el('p','Acces: '+accessLabels[p.access.status]),el('p','Expirare acces: '+date(p.access.expires_at)+' · Ultima autentificare: '+date(p.access.last_login_at)));
 const actions=el('div',undefined,'project-actions');card.append(actions);
 button('Editează proiect',()=>edit(p),actions);
 button('Actualizează',()=>detail(p.id),actions);
 button('Preview client',async()=>{let box=$('preview');if(box){box.remove();return;}box=el('section',undefined,'project-preview');box.id='preview';box.append(el('p','Preview disponibil numai adminului autentificat.'));const view=el('div');view.id='preview-client-view';box.append(view);card.append(box);renderProject(view,await call('/'+p.id+'/preview'));},actions);
 if(p.access.token)button('Copiază URL client',async()=>{await navigator.clipboard.writeText(clientURL(p));notice('URL-ul clientului a fost copiat. Trimite parola separat.');},actions);
 if(p.access.token)button('Copiază parolă',async()=>{
   const value=call('/'+p.id+'/password',{}).then(result=>result.password);
   if(window.ClipboardItem&&navigator.clipboard.write){await navigator.clipboard.write([new window.ClipboardItem({'text/plain':value.then(text=>new Blob([text],{type:'text/plain'}))})]);}
   else await navigator.clipboard.writeText(await value);
   notice('Parola a fost copiată.');
 },actions);
 button(p.access.token?'Setează/resetează parola':'Generează acces',()=>accessForm(p,p.access.token?'reset':'generate'),actions);
 if(p.access.token){button('Generează acces nou',()=>{if(confirm('Linkul vechi și sesiunile existente vor fi invalidate. Continui?'))accessForm(p,'generate');},actions);button(p.access.status==='revoked'?'Reactivează accesul':'Revocă accesul',async()=>{const operation=p.access.status==='revoked'?'reactivate':'revoke';if(confirm(operation==='revoke'?'Revoci accesul și toate sesiunile clientului?':'Reactivezi accesul clientului?')){current=await call('/'+p.id+'/access',{operation});renderDetail();}},actions);}
 if(!['completed','closed','cancelled','in_progress'].includes(p.status))button('Începe intervenția',async()=>{current=await call('/'+p.id+'/start',{});renderDetail();},actions,'primary');
 if(!['completed','closed','cancelled'].includes(p.status))button('Confirmă intervenția ca finalizată',async()=>{if(confirm('Confirmi finalizarea intervenției? Începe termenul de expirare a accesului. Google Review apare numai dacă este activat pentru acest proiect.')){current=await call('/'+p.id+'/complete',{confirm:true});renderDetail();}},actions,'primary');
 button('Vezi Activity Log',async()=>{let log=$('activity');if(log){log.remove();return;}log=el('section');log.id='activity';log.append(el('h3','Jurnal de activitate'));card.append(log);await activity(p.id,log,0);},actions);
 button('Șterge proiect',async()=>{if(!confirm('Ștergi definitiv proiectul „'+p.name+'”? Checklist-ul, jurnalul și accesul clientului vor fi eliminate. Această acțiune nu poate fi anulată.'))return;await call('/'+p.id+'/delete',{confirm:true,version:p.version});offset=0;await list();notice('Proiectul a fost șters.');},actions);
 const travelRow=el('label',undefined,'task-editor'),travelCheck=el('input');travelCheck.type='checkbox';travelCheck.name='en_route';travelCheck.checked=!!p.service_options?.en_route;travelCheck.disabled=!['scheduled','confirmed'].includes(p.status);travelRow.append(travelCheck,el('span','Ne deplasăm spre locație'));card.append(travelRow);
 travelCheck.addEventListener('change',async()=>{const previous=!!p.service_options?.en_route;if(working){travelCheck.checked=previous;return;}working=true;const sequence=viewSequence;const inputs=[...card.querySelectorAll('input[type=checkbox]')];const disabled=inputs.map(input=>input.disabled);inputs.forEach(input=>input.disabled=true);notice('');try{const saved=await call('/'+p.id,{version:p.version,service_options:{en_route:travelCheck.checked}},'PATCH');if(sequence===viewSequence&&card.isConnected){current=saved;renderDetail();notice('Starea deplasării a fost salvată.');}}catch(e){travelCheck.checked=previous;notice(e.message);}finally{working=false;inputs.forEach((input,i)=>input.disabled=disabled[i]);}});
 const display=el('section',undefined,'project-display-options');display.append(el('h3','Afișare pentru client'),el('p','Bifele se salvează automat. Factura apare numai dacă URL-ul este completat; invitația la review apare numai după finalizare.','help'));card.append(display);
 for(const [key,title] of displayToggles){
  const row=el('label',undefined,'task-editor'),check=el('input');check.type='checkbox';check.name=key;check.checked=key==='invoice_enabled'?p.display_options?.[key]!==0:!!p.display_options?.[key];row.append(check,el('span',title));display.append(row);
  check.addEventListener('change',async()=>{
   const previous=key==='invoice_enabled'?p.display_options?.[key]!==0:!!p.display_options?.[key];if(working){check.checked=previous;return;}
   working=true;notice('');const sequence=viewSequence,inputs=[...card.querySelectorAll('input[type=checkbox]')],disabled=inputs.map(input=>input.disabled);inputs.forEach(input=>input.disabled=true);
   try{const saved=await call('/'+p.id,{version:p.version,display_options:{[key]:check.checked}},'PATCH');if(sequence===viewSequence&&card.isConnected){current=saved;renderDetail();notice('Opțiunea a fost salvată.');}}
   catch(e){check.checked=previous;notice(e.message);}finally{working=false;inputs.forEach((input,i)=>input.disabled=disabled[i]);}
  });
 }
 card.append(el('h3',`${p.tasks.filter(t=>t.done).length} din ${p.tasks.length} sarcini finalizate`));
 for(const t of p.tasks){const row=el('label',undefined,'task-editor'), check=el('input');check.type='checkbox';check.checked=!!t.done;row.append(check,el('span',t.title));check.addEventListener('change',async()=>{check.disabled=true;try{current=await call('/'+p.id,{version:p.version,tasks:p.tasks.map(x=>({id:x.id,title:x.title,done:x.id===t.id?check.checked:!!x.done}))},'PATCH');renderDetail();}catch(e){check.checked=!check.checked;notice(e.message);}finally{check.disabled=false;}});card.append(row);}
}
const eventLabels={travel_started:'Deplasare începută',travel_cancelled:'Deplasare oprită',billing_options_changed:'Opțiuni tarifare modificate',display_options_changed:'Opțiuni de afișare modificate',password_copied:'Parolă copiată',project_created:'Proiect creat',project_edited:'Proiect editat',client_login:'Client autentificat',access_generate:'Acces generat',access_reset:'Parolă resetată',access_revoke:'Acces revocat',access_reactivate:'Acces reactivat',access_expired:'Acces expirat',intervention_started:'Intervenție începută',intervention_completed:'Intervenție finalizată',status_changed:'Status modificat',invoice_changed:'Factură modificată',task_added:'Sarcină adăugată',task_done:'Sarcină bifată',task_undone:'Sarcină debifată',task_edited:'Sarcină editată',task_deleted:'Sarcină ștersă'};
async function activity(id,container,start){const data=await call('/'+id+'/activity?offset='+start),list=el('ul',undefined,'project-activity');for(const x of data.rows)list.append(el('li',`${date(x.created_at)} · ${eventLabels[x.type]||x.type} · ${x.actor==='client'?'Client':x.actor==='system'?'Sistem':'Admin ('+x.actor+')'}${x.detail?' · '+x.detail:''}`));container.append(list);if(data.nextOffset!==null){const b=button('Mai multe evenimente',async()=>{b.remove();await activity(id,container,data.nextOffset);},container);}}
function accessForm(p,operation){let old=$('password-panel');if(old)old.remove();const panel=el('section',undefined,'project-panel project-password');panel.id='password-panel';panel.append(el('h3',operation==='reset'?'Setează o parolă nouă':'Generează acces nou'),el('p','Minimum 12 caractere. Parola va putea fi copiată ulterior de admin. Sesiunile anterioare vor fi invalidate.'));
 const form=el('form'),label=el('label','Parolă nouă'),input=el('input');input.type='password';input.minLength=12;input.maxLength=128;input.required=true;input.autocomplete='new-password';label.append(input);form.append(label);panel.append(form);root.append(panel);
 button('Generează parolă',()=>{const bytes=crypto.getRandomValues(new Uint8Array(18));input.value=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');input.type='text';},form);
 button('Arată / ascunde parola',()=>{input.type=input.type==='password'?'text':'password';},form);
 button('Copiază parola',async()=>{await navigator.clipboard.writeText(input.value);notice('Parola a fost copiată. Nu este stocată în browser.');},form);
 const save=el('button','Salvează accesul','primary');save.type='submit';form.append(save);form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{current=await call('/'+p.id+'/access',{operation,password:input.value});input.value='';renderDetail();notice('Accesul a fost actualizat. Copiază URL-ul clientului și trimite parola separat.');}catch(err){notice(err.message);}finally{save.disabled=false;}});panel.scrollIntoView({behavior:'smooth'});
}
function edit(p=null){viewSequence++;root.replaceChildren();const form=el('form',undefined,'project-panel project-form');form.append(el('h2',p?'Editează proiect':'Proiect nou'));root.append(form);const grid=el('div',undefined,'form-grid');form.append(grid);const inputs={};
 for(const [key,title,type,required,max] of [['name','Nume proiect','text',true,160],['client_name','Nume client','text',true,160],['phone','Telefon','tel',true,40],['email','Email (opțional)','email',false,254],['location','Adresă / locație','text',true,500],['scheduled_at','Data și ora · România','datetime-local',true],['price_bani','Preț (lei)','number',true],['description','Descriere vizibilă clientului','textarea',false,4000],['invoice_url','URL factură HTTPS','url',false,2048],['invoice_label','Text buton factură','text',false,100]]){
 const label=el('label',title),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.required=required;if(max)input.maxLength=max;input.name=key;input.value=key==='invoice_label'?(p?.display_options?.invoice_label||'Descarcă factura'):p?(key==='scheduled_at'?bucharestLocal(p[key]):key==='price_bani'?p[key]/100:p[key]):'';if(type==='number'){input.min=0;input.max=10000000;input.step='.01';}inputs[key]=input;label.append(input);grid.append(label);}
 const pricing=el('label','Mod de tarifare'),mode=el('select');mode.name='billing_mode';for(const [value,title] of [['fixed','Tarif fix'],['hourly','Tarif pe oră']]){const option=el('option',title);option.value=value;mode.append(option);}mode.value=p?.service_options?.billing_mode||'fixed';pricing.append(mode);form.append(pricing);
 const minimumLabel=el('label','Minimum comandă (lei)'),minimum=el('input');minimum.type='number';minimum.name='minimum_bani';minimum.min=0;minimum.max=10000000;minimum.step='.01';minimum.value=(p?.service_options?.minimum_bani??10000)/100;minimumLabel.append(minimum);form.append(minimumLabel);
 const agreementLabel=el('label','Referință acord scris pentru un minimum diferit de 100 lei'),agreement=el('textarea');agreement.name='minimum_agreement';agreement.maxLength=1000;agreement.value=p?.service_options?.minimum_agreement||'';agreementLabel.append(agreement);form.append(agreementLabel);
 function pricingState(){const hourly=mode.value==='hourly';minimumLabel.hidden=agreementLabel.hidden=!hourly;minimum.required=hourly;agreement.required=hourly&&Number(minimum.value)!==100;inputs.price_bani.parentElement.firstChild.textContent=hourly?'Tarif (lei / oră)':'Preț (lei)';}mode.addEventListener('change',pricingState);minimum.addEventListener('input',pricingState);pricingState();
 if(p?.started_at||p?.completed_at){mode.disabled=true;if(mode.value==='hourly'){inputs.price_bani.readOnly=true;minimum.readOnly=true;agreement.readOnly=true;}form.append(el('p','Tarifarea pe oră se fixează la începerea intervenției.','help'));}
 const visible=el('label','Arată locația clientului','checkbox-label'),check=el('input');check.type='checkbox';check.checked=p?!!p.show_location:true;visible.prepend(check);form.append(visible);
 const statusLabel=el('label','Status'),status=el('select');for(const [value,title] of Object.entries(labels)){if(!p&&!['draft','scheduled','confirmed'].includes(value))continue;const option=el('option',title);option.value=value;status.append(option);}status.value=p?.status||'scheduled';statusLabel.append(status);form.append(statusLabel,el('p','Începerea și finalizarea se confirmă folosind butoanele din pagina proiectului.','help'));
 const expiresLabel=el('label','Revocă accesul după finalizare'),expires=el('select');for(const [value,title] of [['1','1 zi'],['3','3 zile'],['7','7 zile'],['14','14 zile'],['30','30 zile'],['custom','Personalizat'],['never','Niciodată']]){const option=el('option',title);option.value=value;expires.append(option);}expires.value=p?(p.expiry_days===null?'never':[1,3,7,14,30].includes(p.expiry_days)?String(p.expiry_days):'custom'):'7';expiresLabel.append(expires);const custom=el('input');custom.type='number';custom.min=1;custom.max=3650;custom.step=1;custom.value=p?.expiry_days||7;custom.setAttribute('aria-label','Număr de zile personalizat');custom.hidden=expires.value!=='custom';expires.addEventListener('change',()=>custom.hidden=expires.value!=='custom');expiresLabel.append(custom);form.append(expiresLabel);
 form.append(el('h3','Checklist'));const list=el('div');form.append(list);let taskData=p?p.tasks.map(t=>({id:t.id,title:t.title,done:!!t.done})):[];
 function paintTasks(){list.replaceChildren();taskData.forEach((t,i)=>{const row=el('div',undefined,'task-editor'),done=el('input'),title=el('input');done.type='checkbox';done.checked=t.done;done.setAttribute('aria-label','Sarcină finalizată');done.addEventListener('change',()=>t.done=done.checked);title.type='text';title.value=t.title;title.required=true;title.maxLength=300;title.setAttribute('aria-label','Titlu sarcină');title.addEventListener('input',()=>t.title=title.value);row.append(done,title);button('↑',()=>{if(i){[taskData[i-1],taskData[i]]=[taskData[i],taskData[i-1]];paintTasks();}},row);button('↓',()=>{if(i<taskData.length-1){[taskData[i+1],taskData[i]]=[taskData[i],taskData[i+1]];paintTasks();}},row);button('Șterge',()=>{if(confirm('Ștergi această sarcină?')){taskData.splice(i,1);paintTasks();}},row);list.append(row);});}paintTasks();button('Adaugă sarcină',()=>{if(taskData.length>=500)throw new Error('Maximum 500 de sarcini într-un proiect.');taskData.push({title:'',done:false});paintTasks();},form);
 const actions=el('div',undefined,'project-actions'),save=el('button','Salvează proiect','primary');save.type='submit';actions.append(save);button('Anulează',()=>p?detail(p.id):listView(),actions);form.append(actions);
 form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;notice('');try{const data=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value]));data.scheduled_at=bucharestISO(data.scheduled_at);data.price_bani=Math.round(Number(data.price_bani)*100);data.display_options={...(!p?Object.fromEntries(displayToggles.map(([key])=>[key,false])):{}),invoice_label:data.invoice_label};delete data.invoice_label;data.service_options={billing_mode:mode.value,minimum_bani:Math.round(Number(minimum.value)*100),minimum_agreement:agreement.value};data.show_location=check.checked;data.expiry_days=expires.value==='never'?null:Number(expires.value==='custom'?custom.value:expires.value);data.status=status.value;data.tasks=taskData;if(p)data.version=p.version;current=await call(p?'/'+p.id:'',data,p?'PATCH':'POST');renderDetail();notice('Proiectul a fost salvat.');}catch(err){notice(err.message);}finally{save.disabled=false;}});
}
async function listView(){await list();}
$('list').addEventListener('click',()=>{offset=0;notice('');list().catch(e=>notice(e.message));});$('create').addEventListener('click',()=>{if(authorized){notice('');edit();}});
(async()=>{try{if(!token)throw new Error('Intră întâi în portal cu contul admin, în aceeași filă.');const me=await api('/api/me');if(me.role!=='staff'||me.twoFactorRequired)throw new Error('Acces permis numai adminului autentificat cu verificare în doi pași.');authorized=true;await list();$('nav').hidden=false;}catch(e){notice(e.message);}})();

setInterval(()=>{const preview=$('preview-client-view');if(preview)updateProjectClock(preview);},1000);
