import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {startPortal} from '../src/app.mjs';
import {money,isStaff,clientPayload} from '../src/domain.mjs';
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,0));
function setup({member=false,guest=false,rows=[],list,execute}={}){
 const dom=new JSDOM(html,{url:'https://petruandines.github.io/cleaning-services/portal/'}),calls=[];
 const actor={$id:'u1',name:'Petru',email:'owner@example.test'};
 const sdk={Client:class{setEndpoint(){return this;}setProject(){return this;}},Account:class{async get(){if(guest)throw{code:401};return actor;}async deleteSession(){calls.push('logout');}async createEmailPasswordSession(v){calls.push({loginEmail:v.email});guest=false;}},Teams:class{async listMemberships(){return{memberships:member?[{userId:'u1',confirm:true}]:[]};}},TablesDB:class{async listRows(v){calls.push(v);return list?list(v):{rows,total:rows.length};}},Functions:class{async createExecution(v){calls.push({functionId:v.functionId});return execute?.(v)||{status:'completed',responseStatusCode:201,responseBody:'{}'};}},Query:{equal:(...a)=>a,orderDesc:x=>x,limit:x=>({limit:x}),offset:x=>({offset:x})},ExecutionMethod:{POST:'POST'}};
 const dialog=dom.window.document.querySelector('dialog');dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
 const app=startPortal(sdk,dom.window.document,dom.window);return{...app,doc:dom.window.document,win:dom.window,calls};
}
test('sumele în bani se afișează în lei, inclusiv zero și lipsă',()=>{assert.match(money(45000),/450,00/);assert.match(money(0),/0,00/);assert.equal(money(null),'De stabilit');});
test('numai apartenența confirmată a identității curente dă acces staff',()=>{assert.equal(isStaff({memberships:[{userId:'u2',confirm:true}]},'u1'),false);assert.equal(isStaff({memberships:[{userId:'u1',confirm:false}]},'u1'),false);});
test('cont anonim nu cere date și păstrează formularul de autentificare',async()=>{const s=setup({guest:true});await s.ready;assert.equal(s.calls.length,0);assert.equal(s.doc.getElementById('workspace').hidden,true);});
test('clientul nu primește ecrane staff și textul malițios nu devine HTML',async()=>{const s=setup({rows:[{title:'<img src=x onerror=alert(1)>',status:'confirmed',estimated_cost_bani:45000}]});await s.ready;assert.equal(s.doc.getElementById('new-client').hidden,true);assert.equal(s.doc.querySelector('[data-section=internal_notes]'),null);assert.equal(s.doc.querySelector('#content img'),null);assert.match(s.doc.getElementById('content').textContent,/<img/);});
test('administratorul vede crearea clientului; logout elimină datele afișate',async()=>{const s=setup({member:true,rows:[{display_name:'Private Client'}]});await s.ready;assert.equal(s.doc.getElementById('new-client').hidden,false);s.doc.getElementById('logout').click();await tick();assert.equal(s.doc.getElementById('content').textContent,'');assert.equal(s.doc.getElementById('workspace').hidden,true);});
test('un răspuns vechi nu poate înlocui secțiunea selectată ulterior',async()=>{let release;const s=setup({member:true,list:async v=>v.tableId==='invoices'?new Promise(r=>release=r):{rows:[],total:0}});await s.ready;s.doc.querySelector('[data-section=invoices]').click();await tick();s.doc.querySelector('[data-section=locations]').click();await tick();release({rows:[{invoice_number:'STALE'}],total:1});await tick();assert.equal(s.doc.getElementById('section-title').textContent,'Locații');assert.doesNotMatch(s.doc.getElementById('content').textContent,/STALE/);});
test('firma necesită denumire și CUI; parola nu este normalizată',()=>{assert.throws(()=>clientPayload(new Map([['client_code','p1'],['email','a@b.ro'],['client_type','PJ']])));const r=clientPayload(new Map([['client_code',' p1 '],['email','A@B.RO'],['client_type','PF'],['password','  secret password  ']]));assert.equal(r.password,'  secret password  ');assert.equal(r.client_code,'P1');});
test('eroarea de creare parțială rămâne vizibilă și parola este golită',async()=>{const s=setup({member:true,execute:()=>({status:'completed',responseStatusCode:503,responseBody:JSON.stringify({error:'profile_creation_unconfirmed_review_required',reference:'c_test'})})});await s.ready;s.doc.getElementById('new-client').click();const f=s.doc.getElementById('client-form');for(const[k,v]of Object.entries({client_code:'p1',email:'a@b.ro',display_name:'Client',password:'temporary-test-password'}))f.elements[k].value=v;f.dispatchEvent(new s.win.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(f.elements.password.value,'');assert.match(s.doc.getElementById('client-notice').textContent,/c_test/);assert.equal(s.doc.querySelector('dialog').open,true);});
